Hello World in C++.cpp
Added the Hemllo World in C++.
=> Added Hello World in C++

Linear Search in C++.cpp, output.txt
Added the Linear Search in CPP
=> Added the Linear Search in C++

.vscode/settings.json, Cat&Mouse2.cpp, N-queens.cpp, N-queens2.cpp
Solved the problem of Cat and Mouse-2 using DP
=> Solved LC Qs

MaximalRectangle.cpp, TrappingRainwater.cpp
Added 2 more DP tagged problems in the repository.
=> More Problem contributions 

README.md, ValidAnagram.cpp
Added a function which checks if the given string input is a valid anagram or not. It's in C++ programming language.
=> Added Valid Anagram

Minimum Interval to Include Each Query.cpp
=> added Minimum Interval to Include Each Query.cpp

reverseTwopointer.cpp
Added a program for reversing an array using two pointers in C++ lang.
=> Added a program to reverse an array using two pointer method in CPP

Hello World in C++.cpp
corrected a typo
earlier hello was miss typed by hemllo
=> Update Hello World in C++.cpp

PlusOne.cpp
Solution to the Leetcode Problem  #66. PlusOne in cpp.
=> PlusOne.cpp

Pigeonhole_sort.cpp, floyd_warshal.cpp
=> Anvita next branch

floyd_warshal.cpp
=> Added Floyd Warshall

Timeclock.cpp
This is a CPP code regarding time clock representation.
=> timeclock.cpp

Kokoeating.java
Solved Leetcode-875 using Binary Search using search space in Java
=> Koko eating Bananas Leetcode-875

GrayCode.java
Solved Leetcode Ques-89 in Java using List DS and Bitwise Algorithms.
=> Gray Code Leetcode-89

LeetcodePivotArray.cpp
Added Leetcode solution for problem no 724. Find Pivot Index
=> Added Leetcode solution for problem no 724. Find Pivot Index

Kd_algo.cpp
I have added kadane's_algo  in the pull request, I hope that you will accept my PR ASAP.
=> added kd_algo

rectanglepattern.cpp
Rectangular pattern using c++ language
=> Rectangular pattern using c++

FindMedianfromDataStream.cpp, FindMinimumInRotatedSortedArrayII.cpp, IntegerToEnglishWords.cpp
Solution to Leetcode Hard Problem 154, 273, 295
=> Solution to Leetcode Hard Problem 154, 273, 295

CountSubtreesWithMaxDistanceBetweenCities.java
Solution to Leetcode Hard Problem 1617. This was the question in Weekly Contest 210.
=> Solution to Weekly Contest Hard Problem

dijkstra.cpp
=> Added dijkstra

SieveOfEratosthenes.cpp
=> Sieve of Eratosthenes

 Binary Tree Pruning.cpp, BinaryTreeTilt, LetterCasePermutation.cpp, PermutationsII.cpp
Given a collection of numbers, nums, that might contain duplicates, return all possible unique permutations in any order.
=> Permutation II | Medium

kadaneAlgorithm.cpp
Given an array Arr[] of N integers. Find the contiguous sub-array(containing at least one number) which has the maximum sum and return its sum. Solved via iterations
=> Kadane Algorithm - GFG

bank.cpp
Created a class named "Bank", added data members: Account Number, Balance and Name. Also created functions to withdraw and deposit money into the account and show the final bank balance as output.
=> Program demonstrating real world usage of class in C++

stateofwakanda.java
=> State of Wakanda 2D Array in Java

waveArray.cpp
Given a sorted array arr[] of distinct integers. Sort the array into a wave-like array(In Place). In other words, arrange the elements into a sequence such that arr[1] >= arr[2] <= arr[3] >= arr[4] <= arr[5].....
If there are multiple solutions, find the lexicographically smallest one.
=> Convert To Wave - GFG

Leftviewoftree.cpp
Given a Binary Tree, print Left view of it. Left view of a Binary Tree is set of nodes visible when tree is visited from Left side. The task is to complete the function leftView(), which accepts root of the tree as argument.
=> Created left view of a binary tree - GFG

transitionPoint.cpp
Given a sorted array containing only 0s and 1s, find the transition point.
=> Find Transition Point - GFG

towerofhanoi.java
Tower Of Hanoi
1. There are 3 towers. Tower 1 has n disks, where n is a positive number. Tower 2 and 3 are empty. 2. The disks are increasingly placed in terms of size such that the smallest disk is on top and largest disk is at bottom. 3. You are required to 3.1. Print the instructions to move the disks. 3.2. from tower 1 to tower 2 using tower 3 3.3. following the rules 3.3.1 move 1 disk at a time. 3.3.2 never place a smaller disk under a larger disk. 3.3.3 you can only move a disk at the top. Note -> The online judge can't force you to write the function recursively but that is what the spirit of question is.Write recursive and not iterative logic. The purpose of the question is to aid learning recursion and not test you. solved using by recurssion;
=> Tower of hanoi

redistribute.java
You are given an array of strings words (0-indexed).
In one operation, pick two distinct indices i and j, where words[i] is a non-empty string, and move any character from words[i] to any position in words[j].
Return true if you can make every string in words equal using any number of operations, and false otherwise.
=> Redistribute Characters to Make All Strings Equal

largest-palindromic-number.cpp
Return the largest palindromic integer
=> Find largest  palindromic no. from input

deleteWithoutHeadPointer.cpp
You are given a pointer/ reference to the node which is to be deleted from the linked list of N nodes. The task is to delete the node. Pointer/ reference to head node is not given.
=> Delete without head pointer - GFG

bfsOfGraph.cpp
Given a directed graph. The task is to do Breadth First Traversal of this graph starting from 0.
=> BFS of Graph - GFG

leetcode/SkylineProblem.cpp
I am a beginner contributor at Hacktober Fest 
Thanks for the initiative
=> Skyline Problem Solved Using Multiset and Sorting

CPU Scheduling Algorithms C++/1stIn1stOut.cpp, CPU Scheduling Algorithms C++/Best Fit.cpp, CPU Scheduling Algorithms C++/First Fit.cpp, CPU Scheduling Algorithms C++/Worst Fit.cpp, CPU Scheduling Algorithms C++/banker.c, CPU Scheduling Algorithms C++/lab1.cpp, CPU Scheduling Algorithms C++/small to big- bouble slot - os.cpp
I add CPU Scheduling Algorithms in C++
=> Add CPU Scheduling Algorithms C++

Subsets.cpp
Given an integer array nums of unique elements, return all possible subsets (the power set).
The solution set must not contain duplicate subsets. Return the solution in any order.
=> Added Subsets.cpp

Professor_And_Directions.cpp
Added problem of the same name from codechef.
=> Added Professor_And_Directions.cpp

Chef_And_Salary_Pay.cpp
Added problem of the same name from codechef.
=> Added Chef_And_Salary_Pay.cpp

Queen's_Placement.cpp
Added problem of the same name from codechef.
=> Added Queen's_Placement.cpp

ginortS.py
Added 'ginortS' problem of hackerrank python.
=> Added ginortS.py

Iterables_and_iterators.py
Added 'Iterables and Iterators' problem from hackerrank python.
=> Added Iterables_and_iterators.py

Piling_up!.py
Added 'Piling Up!' problem from hackerrank python.
=> Added Piling_up!.py

Word_order.py
Added 'Word Order' problem from hackerrank python.
=> Added Word_order.py

leetcode/SatisfiabilityOfEqualityEquations.cpp
Added Leetcode question in leetcode folder.
Solution approach for Satisfiability of Equality Equations added with Code. 
Thanks!
=> Added LeetCode Question Satisfiablity of Equality Equations

knapsack.cpp
0-1 knapsack problem solved in c++ with greedy approach
=> added knapsack problem

SunnyNo.java
A number N is a sunny number if N + 1 is a perfect square.
=> Added Sunny Number.java

Heap-kfrequent.cpp
=> k frequent elements in heap

Integer to Roman
Program accepts positive integer as input and prints its Roman value..
=> Integer to Roman

stockSpan.cpp
=> stock span prob

duplicateNumber.cpp
Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.
There is only one repeated number in nums, return this repeated number.
You must solve the problem without modifying the array nums and uses only constant extra space.
=> Added duplicateNumber.cpp

Subsets.cpp, TwoSumII.cpp
Given a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number. Let these two numbers be numbers[index1] and numbers[index2] where 1 <= index1 < index2 <= numbers.length.
Return the indices of the two numbers, index1 and index2, added by one as an integer array [index1, index2] of length 2.
The tests are generated such that there is exactly one solution. You may not use the same element twice.
Your solution must use only constant extra space.
=> Added TwoSumII.cpp

132Pattern.cpp, 4Sum.cpp, SearchInRotatedSortedArray.cpp, SwappingNodesInALinkedList.cpp
You are given the head of a linked list, and an integer k.
Return the head of the linked list after swapping the values of the kth node from the beginning and the kth node from the end (the list is 1-indexed).
=> Added Swapping Nodes in a linked list

4Sum.cpp
Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]] such that:
0 <= a, b, c, d < n
a, b, c, and d are distinct.
nums[a] + nums[b] + nums[c] + nums[d] == target
You may return the answer in any order.
=> Added 4Sum.cpp

132Pattern.cpp, 4Sum.cpp, SearchInRotatedSortedArray.cpp
Given an array of n integers nums, a 132 pattern is a subsequence of three integers nums[i], nums[j] and nums[k] such that i < j < k and nums[i] < nums[k] < nums[j].
Return true if there is a 132 pattern in nums, otherwise, return false.
=> Added One Three Two Pattern

132Pattern.cpp, 4Sum.cpp, SearchInRotatedSortedArray.cpp, SwappingNodesInALinkedList.cpp
There is an integer array nums sorted in non-decreasing order (not necessarily with distinct values).
Before being passed to your function, nums is rotated at an unknown pivot index k (0 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, [0,1,2,4,4,4,5,6,6,7] might be rotated at pivot index 5 and become [4,5,6,6,7,0,1,2,4,4].
Given the array nums after the rotation and an integer target, return true if target is in nums, or false if it is not in nums.
You must decrease the overall operation steps as much as possible.
=> Added Search in a Rotated Sorted array

ContainerWithMostWater, StringToInteger.cpp, TrimBinarySearchTree.cpp
Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).
The algorithm for myAtoi(string s) is as follows:
Read in and ignore any leading whitespace.
Check if the next character (if not already at the end of the string) is '-' or '+'. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.
Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.
Convert these digits into an integer (i.e. "123" -> 123, "0032" -> 32). If no digits were read, then the integer is 0. Change the sign as necessary (from step 2).
If the integer is out of the …
=> Added String to Integer

Excel sheet column table.cpp, backspace string compare.cpp, happy_number.cpp, maximum product of three numbers.cpp, minimum moves to equal array elements.cpp
Added 4 Mathematical programming questions
=> Add Mathematical Problems

Palindrome.java
A palindromic number (also known as a numeral palindrome or a numeric palindrome) is a number (such as 16461) that remains the same when its digits are reversed.
=> Added palindrome number. java

.vscode/settings.json, leetcode/Valid Parenthesis.cpp, leetcode/c_cpp_properties.json
This is my cpp program name: Valid Parenthesis.
=> Added cpp program(LeetCode)

Fibonacci.java, code.java
In mathematics, the Fibonacci numbers, commonly denoted Fₙ, form a sequence, the Fibonacci sequence, in which each number is the sum of the two preceding ones. The sequence commonly starts from 0 and 1, although some authors omit the initial terms and start the sequence from 1 and 1 or from 1 and 2.
=> Added Fibonacci number.java

P26.java, Pascal.java
In mathematics, Pascal's triangle is a triangular array of binomial coefficients that arise in probability theory, combinatorics, and algebra.
=> Added Pascal Triangle.java

fmnisa2.cpp
In this, we have to find out the missing number of the given array so we have to formaulate a formula and have to find the lost number.
here fmnisa stands for finding the missing number in the series array.
=> Added Fmnisa .c++

Stack and Queue Questions/0.Reverse Stack.txt, Stack and Queue Questions/1.Reverse Queue.txt, Stack and Queue Questions/2.Check redundant brackets.txt, Stack and Queue Questions/3.Stock Span.txt, Stack and Queue Questions/4.Minimum bracket Reversal.txt
=> Stack question added

LinkedList Questions/0.Find a Node in Linked List.txt, LinkedList Questions/1.AppendLastNToFirst.txt, LinkedList Questions/2.Eliminate duplicates from LL.txt, LinkedList Questions/3.Print Reverse LinkedList.txt, LinkedList Questions/4.Palindrome LinkedList.txt
The best 5 questions of linkedlist added over here
=> LinkedList Questions Added

Shortest Palindrome.cpp
Added the Shortest Palindrome Brute Force Approach
=> Added Shortest Pallindrome
